settings:
  title: 'violets007 Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: violets007 # unique identifier
    name: 'violets007 blog'
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://violets007.cn' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: 'status.openai.com'
    name: 'OpenAI Status'
    description: 'OpenAi 服务状态'
    url: 'https://status.openai.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

